---
deployment:
  tasks:
    -export DEPLOYPATH=/home/uthabiti/public_html/
    -/bin/cp -R vendor $DEPLOYPATH
    -/bin/cp -R assets $DEPLOYPATH
    -/bin/cp index.html $DEPLOYPATH
    -/bin/cp contact.html $DEPLOYPATH
    -/bin/cp about.html $DEPLOYPATH
    -/bin/cp services.html $DEPLOYPATH
